version: "3.0"

services:
  shiny:
    container_name: rgen_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: 'root'
    ports:
      - '8180:8180'
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
volumes:
  shiny_logs:
